version: "3.1"

services:
  wordpress:
    #    image: wordpress
    build: ./docker/php
    #restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./docker/php/conf/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini
      - ./docker/php/log/xdebug:/var/log/xdebug
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
